# Search Service Configuration
spring:
  application:
    name: search-service
  config:
    import: "optional:vault://"
  cloud:
    vault:
      uri: http://vault:8200
      token: root
      kv:
        enabled: true
    aws:
      sqs:
        endpoint: ${spring.cloud.aws.sqs.endpoint}
      region:
        static: ${aws.region}
      credentials:
        access-key: ${aws.access.key.id}
        secret-key: ${aws.secret.access.key}
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}
  
  # Elasticsearch configuration
  elasticsearch:
    uris: ${spring.elasticsearch.uris}


server:
  port: 8085

# Logging configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    com.insurecloud.search: DEBUG
    org.springframework.data.elasticsearch: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.client.serviceUrl.defaultZone}
