package com.insurecloud.policy.audit;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.Instant;
import java.util.Map;

/**
 * Represents an audit log entry to be stored in AWS DynamoDB.
 * Each entry captures a specific event related to a policy, including who performed the action,
 * on which policy, the type of event, when it occurred, and additional details.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "AuditLog")
public class AuditLogEntry {

    /**
     * Unique identifier for the audit event.
     * Automatically generated by DynamoDB.
     */
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String eventId;

    /**
     * The ID of the user who performed the action.
     * In a production system, this would typically come from the security context (e.g., JWT).
     */
    @DynamoDBAttribute
    private String userId; // User who performed the action, if available

    /**
     * The ID of the policy that was affected by this event.
     */
    @DynamoDBAttribute
    private String policyId; // ID of the policy affected

    /**
     * The type of audit event (e.g., "POLICY_CREATED", "POLICY_UPDATED", "POLICY_DELETED").
     */
    @DynamoDBAttribute
    private String eventType; // e.g., POLICY_CREATED, POLICY_UPDATED

    /**
     * The timestamp when the event occurred, stored in UTC.
     * Converted to String for DynamoDB storage and back to Instant upon retrieval.
     */
    @DynamoDBTypeConverted(converter = InstantConverter.class)
    @DynamoDBAttribute
    private Instant timestamp;

    /**
     * A map of additional details related to the event, such as old and new values,
     * or other relevant contextual information.
     */
    @DynamoDBAttribute
    private Map<String, String> details; // JSON string of old/new values, or other relevant data

    /**
     * Custom converter for java.time.Instant to String for DynamoDB storage.
     * DynamoDB does not natively support Instant, so it's stored as an ISO 8601 String.
     */
    public static class InstantConverter implements DynamoDBTypeConverter<String, Instant> {
        @Override
        public String convert(final Instant object) {
            return object.toString();
        }

        @Override
        public Instant unconvert(final String object) {
            return Instant.parse(object);
        }
    }
}
